{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "jtldemo-linux.secretProviderClassName" . }}
  labels:
    {{- include "jtldemo-linux.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ required "config.existingSecret.name is required when keyVault is enabled" .Values.config.existingSecret.name }}
      type: Opaque
      data:
        - objectName: ConnectionStrings__JtlDemo
          key: {{ required "config.existingSecret.key is required when keyVault is enabled" .Values.config.existingSecret.key }}
  parameters:
    usePodIdentity: "false"
    clientID: {{ required "keyVault.clientId is required when keyVault is enabled" .Values.keyVault.clientId | quote }}
    keyvaultName: {{ required "keyVault.name is required when keyVault is enabled" .Values.keyVault.name | quote }}
    tenantId: {{ required "keyVault.tenantId is required when keyVault is enabled" .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ required "keyVault.objectName is required when keyVault is enabled" .Values.keyVault.objectName | quote }}
          objectAlias: ConnectionStrings__JtlDemo
          objectType: secret
{{- end }}
