{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jtldemo-linux.serviceAccountName" . }}
  labels:
    {{- include "jtldemo-linux.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.keyVault.enabled }}
    azure.workload.identity/client-id: {{ required "keyVault.clientId is required when keyVault is enabled" .Values.keyVault.clientId | quote }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
